### ISSUE TITLE
Exportar CSV dos dados da Residência

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/tomieohtake-theme#1]
Aplicar o código de exportar .csv nessa versão do Tema. Vc me ajuda @willowmagrini ?

**Comment by willowmagrini** [comment]
Quando exporta o seu fica errado porque quando você preencheu ele os campos eram diferentes mas para os usuários novos funciona.

**Comment by diegorojas** [comment]
Fala man, entendi, mas seguinte, agora preciso exportar os dados anteriores, e na sequência deixar pronto para os dados novos. Foi isso que tava falando no titulo da issue, saca? Mas pelo que entendi, é so vc me orientar um pouco agora que eu mesmo faço essa adaptação em um outro branch

**Comment by diegorojas** [comment]
Aguardo seu branch para eu matar isso até 6a, tá?

**Comment by diegorojas** [comment]
Fala willow, man, chegou o dia aqui e preciso de uma ajudinha para matar isso. Estou abrindo as inscrições para o prêmio agora e to entendendo que o script de exportação usa a taxonomia das inscrições para exportar os candidatos. 

A grande questão aqui é conseguir diferenciar o processo de residência do processo do prêmio. Queriam um CSV exportado dos dados da residência antes de começarem as novas incrições, isso eu não consegui entregar para eles.

**Comment by diegorojas** [comment]
Tentando exportar agora, o que tenho de log de erro é isso:

`<br /> <b>Warning</b>: fopen(/www/premioedpnasartes.institutotomieohtake.org.br/wp-content/uploads/2018/04/incricoes.csv): failed to open stream: Permission denied in <b>/www/premioedpnasartes.institutotomieohtake.org.br/wp-content/themes/tomieohtake-theme/page-exportacao.php</b> on line <b>70</b><br /> <br /> <b>Warning</b>: fputcsv() expects parameter 1 to be resource <br /> <b>Warning</b>: fclose() expects parameter 1 to be resource email`

**Comment by diegorojas** [comment]
Valeu mano!
