### ISSUE TITLE
Aplicar Filtro por estado e contador  no template "Inscritos"

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/tomieohtake-theme#3]
Trazer as melhorias feitas no fork de arquitetura para esse projeto aqui

![filtro-e-contador](https://user-images.githubusercontent.com/3632627/38279188-82cb22e4-3775-11e8-9ec9-3c3f163feae7.png)

**Comment by willowmagrini** [comment]
@diegorojas verifica aqui por favor.

**Comment by diegorojas** [comment]
Beleza! Valeu man! Preciso colocar mais dados para poder de fato testar o filtro de estado...
