### ISSUE TITLE
Inconsistências na Inscrição e na Seleção de candidatos

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/tomieohtake-theme#5]
Willow, fazendo testes hoje no Beta, percebi as seguinte coisas:

- Depois de Inscrito. Não está dando certo acessar a página de Inscrição pelo menu superior, vc cai numa tela em branco:

![captura de tela de 2018-04-04 18-42-16](https://user-images.githubusercontent.com/3632627/38336369-f00598fe-3837-11e8-8a72-f9953ca68295.png)

- Parece que tem a ver com internamente no mesmo ID de uma Inscrição estarem as duas categorias, veja na imagem abaixo
![captura de tela de 2018-04-04 18-38-41](https://user-images.githubusercontent.com/3632627/38336259-8baf0304-3837-11e8-8570-d5b644b0cbbf.png)

- Ai temos o seguinte, no template Selecionados, o query não está filtrando pela categoria da inscrição:
![captura de tela de 2018-04-04 18-41-17](https://user-images.githubusercontent.com/3632627/38336326-ccc71c46-3837-11e8-9605-c37c550a63ef.png)

**Comment by willowmagrini** [comment]
@diegorojas o meta finalista é relacionado ao usuário então eu criei um meta novo 'finalistas-2018' para separar dos outros anos. Da uma verificada se está ok.

**Comment by diegorojas** [comment]
Nois mano! Verifiquei e tá tudo rolando no beta! Vou colocar em produção amanhã cedo para testar
